image:
  file: .gitpod.Dockerfile
ports:
  - port: 5432
    onOpen: ignore
  - port: 24693
    onOpen: ignore
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: true
    addComment: true

tasks:
  - init: ./utils/gitpod-install.sh; sudo mkdir -p /var/log/fossology; sudo chown fossy:gitpod /var/log/fossology
    command: mkdir -p public; apachectl restart
  - command: sudo chown gitpod:fossy /workspace/fossy/etc/fossology/Db.conf; sudo /workspace/fossy/code/share/fossology/scheduler/agent/fo_scheduler --verbose=3 --reset
    name: fossology
