image:
  file: .gitpod.Dockerfile
ports:
  - port: 5432
    onOpen: ignore

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: true
    addComment: true

tasks:
  - init: ./utils/gitpod-install.sh
    command: mkdir -p public && apachectl restart
