image:
  file: .gitpod.Dockerfile
ports:
  - port: 5432
    onOpen: ignore

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: true
    addComment: true

tasks:
  - init: sudo ./utils/fo-installdeps -ye && make && sudo make install && sudo service postgresql restart && sudo /usr/local/lib/fossology/fo-postinstall && sudo service fossology start && sudo ./install/scripts/php-conf-fix.sh --overwrite && sudo -HE apachectl restart
