# Copyright Siemens AG, 2014-2019
# SPDX-License-Identifier: GPL-2.0 LGPL-2.1

# build FOSSology on Travis CI - https://travis-ci.org/

language: php
dist: bionic
os: linux

env:
  global:
    - PATH="/usr/lib/ccache/:$PATH"

services:
  - postgresql

addons:
  apt:
    packages: &default_packages
      - cabextract
      - genisoimage
      - libboost-program-options-dev
      - libboost-regex-dev
      - libboost-system-dev
      - libboost-filesystem-dev
      - libglib2.0-dev
      - libcppunit-dev
      - libcunit1-dev
      - libdbd-sqlite3-perl
      - libjsoncpp-dev
      - libjson-c-dev
      - liblocal-lib-perl
      - libmagic-dev
      - librpm-dev
      - libspreadsheet-writeexcel-perl
      - libtext-template-perl
      - php-cli
      - php-pgsql
      - php-zip
      - php-xml
      - php-mbstring
      - poppler-utils
      - p7zip
      - p7zip-full
      - rpm
      - sleuthkit
      - unrar-free
      - upx-ucl
      - libicu-dev
      - libgcrypt20-dev

jobs:
  include:
    - stage: Build
      name: Build
      install:
        - sudo apt-get -qq -y install lsb-release cppcheck libcunit1-dev libcppunit-dev sudo git php-phpdbg
        - sudo apt-get -qq -y install sqlite3 php-sqlite3 libsqlite3-dev libdbd-sqlite3-perl postgresql-server-dev-all composer
        - sudo utils/fo-installdeps -e -o -y
      script:
        - make
    - stage: Compliance
      name: Copyright
      addons: {}
      services: docker
      script:
        - >-
          if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
          docker pull gmishx/fossology-ci:latest
          && docker run --name "fossologyscanner" -w "/opt/repo" -v ${PWD}:/opt/repo
          -e TRAVIS=${TRAVIS} -e TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
          -e TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
          gmishx/fossology-ci:latest "/bin/fossologyscanner" copyright keyword ;
          fi
    - stage: Compliance
      name: License
      addons: {}
      services: docker
      script:
        - >-
          if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
          docker pull gmishx/fossology-ci:latest
          && docker run --name "fossologyscanner" -w "/opt/repo" -v ${PWD}:/opt/repo
          -e TRAVIS=${TRAVIS} -e TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
          -e TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
          gmishx/fossology-ci:latest "/bin/fossologyscanner" nomos ojo ;
          fi
