# Copyright Siemens AG, 2014-2019
# SPDX-License-Identifier: GPL-2.0 LGPL-2.1

# build FOSSology on Travis CI - https://travis-ci.org/

language: php
dist: xenial
php: 7.0
cache:
  ccache: true
  directories:
    - $HOME/.composer
env:
  global:
    - PATH="/usr/lib/ccache/:$PATH"
    - COMPOSER_HOME="$HOME/.composer/"

addons:
  apt:
    packages: &default_packages
      - cabextract
      - genisoimage
      - libboost-program-options-dev
      - libboost-regex-dev
      - libboost-system-dev
      - libboost-filesystem-dev
      - libglib2.0-dev
      - libcppunit-dev
      - libcunit1-dev
      - libdbd-sqlite3-perl
      - libjsoncpp-dev
      - libjson-c-dev
      - liblocal-lib-perl
      - libmagic-dev
      - librpm-dev
      - libspreadsheet-writeexcel-perl
      - libtext-template-perl
      - php-cli
      - php-pgsql
      - php-zip
      - php-xml
      - php-mbstring
      - poppler-utils
      - p7zip
      - p7zip-full
      - rpm
      - sleuthkit
      - unrar-free
      - upx-ucl

services: postgresql

jobs:
  fast_finish: true
  include:
    - stage: GitHub Page Release
      name: GitHub Page deploy
      addons:
        apt:
          packages:
            - doxygen
            - graphviz
      script:
        - doxygen -v
        - bash utils/deploy-pages.sh
      deploy:
        provider: pages
        cleanup: false
        skip_cleanup: true
        token: $GITHUB_TOKEN
        keep_history: false
        local_dir: code_docs
        repo: $GH_REPO_REF
        target-branch: master
        on:
          branch: master
