# Copyright Siemens AG, 2014-2019
# SPDX-License-Identifier: GPL-2.0 LGPL-2.1

# build FOSSology on Travis CI - https://travis-ci.org/

language: php
dist: bionic
os: linux

env:
  global:
    - PATH="/usr/lib/ccache/:$PATH"

services:
  - postgresql

addons:
  apt:
    packages: &default_packages
      - cabextract
      - composer
      - cppcheck
      - genisoimage
      - git
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-regex-dev
      - libboost-system-dev
      - libcppunit-dev
      - libcunit1-dev
      - libdbd-sqlite3-perl
      - libgcrypt20-dev
      - libglib2.0-dev
      - libicu-dev
      - libjson-c-dev
      - libjsoncpp-dev
      - liblocal-lib-perl
      - libmagic-dev
      - librpm-dev
      - libspreadsheet-writeexcel-perl
      - libsqlite3-dev
      - libtext-template-perl
      - lsb-release
      - p7zip
      - p7zip-full
      - php-cli
      - php-mbstring
      - php-pgsql
      - php-phpdbg
      - php-sqlite3
      - php-xml
      - php-mbstring
      - php-gd
      - poppler-utils
      - postgresql-server-dev-all
      - rpm
      - sleuthkit
      - sqlite3
      - sudo
      - unrar-free
      - upx-ucl

jobs:
  include:
    - stage: Build
      name: Build
      install:
        - sudo /usr/sbin/update-ccache-symlinks
        - sudo utils/fo-installdeps -e -o -y
      script:
        - make
    - stage: Compliance
      name: Copyright
      addons: {}
      services: docker
      script:
        - >-
          if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
          docker pull fossology/fossology:scanner
          && docker run --name "fossologyscanner" -w "/opt/repo" -v ${PWD}:/opt/repo
          -e TRAVIS=${TRAVIS} -e TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
          -e TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
          fossology/fossology:scanner "/bin/fossologyscanner" copyright keyword ;
          fi
    - stage: Compliance
      name: License
      addons: {}
      services: docker
      script:
        - >-
          if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
          docker pull fossology/fossology:scanner
          && docker run --name "fossologyscanner" -w "/opt/repo" -v ${PWD}:/opt/repo
          -e TRAVIS=${TRAVIS} -e TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
          -e TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
          fossology/fossology:scanner "/bin/fossologyscanner" nomos ojo ;
          fi
